name: "Build and push x86_64-w64-mingw32.gcc to cachix"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: vroad
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: cat /etc/nix/nix.conf
    - run: nix-build -A x86_64-w64-mingw32.gcc

